# Horizontal Pod Autoscaler for Agentical
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: agentical-hpa
  namespace: agentical
  labels:
    app.kubernetes.io/name: agentical
    app.kubernetes.io/component: autoscaling
    app.kubernetes.io/part-of: agentical-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agentical-deployment
  
  minReplicas: 3
  maxReplicas: 20
  
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  
  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  
  # Custom metrics scaling (requires metrics server)
  - type: Pods
    pods:
      metric:
        name: agent_operations_per_second
      target:
        type: AverageValue
        averageValue: "50"
  
  # External metrics scaling (e.g., from monitoring system)
  - type: External
    external:
      metric:
        name: queue_length
        selector:
          matchLabels:
            queue: agentical-tasks
      target:
        type: AverageValue
        averageValue: "10"
  
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
      - type: Pods
        value: 5
        periodSeconds: 30
      selectPolicy: Max

---
# HPA for Frontend
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: agentical
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: autoscaling
    app.kubernetes.io/part-of: agentical-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  
  minReplicas: 2
  maxReplicas: 10
  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
    
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30

---
# Vertical Pod Autoscaler (VPA) for resource recommendations
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: agentical-vpa
  namespace: agentical
  labels:
    app.kubernetes.io/name: agentical
    app.kubernetes.io/component: vpa
    app.kubernetes.io/part-of: agentical-platform
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agentical-deployment
  
  updatePolicy:
    updateMode: "Auto"  # Can be "Off", "Initial", or "Auto"
  
  resourcePolicy:
    containerPolicies:
    - containerName: agentical
      maxAllowed:
        cpu: "4"
        memory: "4Gi"
      minAllowed:
        cpu: "100m"
        memory: "128Mi"
      controlledResources: ["cpu", "memory"]

---
# Pod Disruption Budget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: agentical-pdb
  namespace: agentical
  labels:
    app.kubernetes.io/name: agentical
    app.kubernetes.io/component: pdb
    app.kubernetes.io/part-of: agentical-platform
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: agentical
      app.kubernetes.io/component: api

---
# Pod Disruption Budget for Frontend
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: agentical
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: pdb
    app.kubernetes.io/part-of: agentical-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/component: frontend