# Secrets for Agentical Application
# Note: In production, use external secret management (e.g., AWS Secrets Manager, HashiCorp Vault)

apiVersion: v1
kind: Secret
metadata:
  name: agentical-secrets
  namespace: agentical
  labels:
    app.kubernetes.io/name: agentical
    app.kubernetes.io/component: secret
type: Opaque
data:
  # Base64 encoded secrets (replace with actual values)
  # Use: echo -n "your-secret" | base64
  
  # Database credentials
  SURREALDB_USERNAME: cm9vdA==  # root
  SURREALDB_PASSWORD: cm9vdA==  # root
  
  # Application secrets
  SECRET_KEY: eW91ci1zZWN1cmUtc2VjcmV0LWtleQ==  # your-secure-secret-key
  
  # API Keys (replace with actual values)
  ANTHROPIC_API_KEY: ""  # Base64 encoded Anthropic API key
  LOGFIRE_TOKEN: ""      # Base64 encoded Logfire token
  OPENAI_API_KEY: ""     # Base64 encoded OpenAI API key
  
  # Redis password (if authentication is enabled)
  REDIS_PASSWORD: ""     # Base64 encoded Redis password

---
# TLS Secret for HTTPS (replace with actual certificates)
apiVersion: v1
kind: Secret
metadata:
  name: agentical-tls
  namespace: agentical
  labels:
    app.kubernetes.io/name: agentical
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  # Replace with actual base64 encoded certificate and key
  tls.crt: LS0tLS1CRUdJTi...  # Base64 encoded certificate
  tls.key: LS0tLS1CRUdJTi...  # Base64 encoded private key

---
# Docker Registry Secret (if using private registry)
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: agentical
  labels:
    app.kubernetes.io/name: agentical
    app.kubernetes.io/component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJyZWdpc3RyeS5leGFtcGxlLmNvbSI6IHsKICAgICAgInVzZXJuYW1lIjogInVzZXJuYW1lIiwKICAgICAgInBhc3N3b3JkIjogInBhc3N3b3JkIiwKICAgICAgImVtYWlsIjogImVtYWlsQGV4YW1wbGUuY29tIiwKICAgICAgImF1dGgiOiAiZFhObGNtNWhiV1U2Y0dGemMzZHZjbVE9IgogICAgfQogIH0KfQ==

---
# Service Account Token Secret (for enhanced security)
apiVersion: v1
kind: Secret
metadata:
  name: agentical-service-account-token
  namespace: agentical
  labels:
    app.kubernetes.io/name: agentical
    app.kubernetes.io/component: service-account
  annotations:
    kubernetes.io/service-account.name: agentical-service-account
type: kubernetes.io/service-account-token